stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    params:
      - data_ingestion.test_size
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python3 src/data_preprocessing.py

    deps:
      - src/data_preprocessing.py
    outs:
      - data/interim

  model_building:
    cmd: python3 src/model_building.py
    params:
      - model_building.max_features
      - model_building.ngram_range
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    deps:
      - data/interim/train_preprocessed.csv
      - src/model_building.py
    outs:
      - model/lgbm_model.pkl
      - model/tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python3 src/model_evaluation.py 
    deps:
      - model/lgbm_model.pkl
      - model/tfidf_vectorizer.pkl
      - data/interim/train_preprocessed.csv
      - data/interim/train_preprocessed.csv
      - src/model_evaluation.py
    outs:
      - model/experiment_info.json
    

  model_registration:
    cmd: python3 src/register_model.py
    deps:
      - model/experiment_info.json
      - src/register_model.py