data_ingestion:
  test_size: 0.2
  random_state: 42

model_building:
  model_name: "sentiment_model"
  ngram_range: [1,3]
  max_features: 1000
  learning_rate: 0.01
  max_depth: 20
  n_estimators: 367


